# Generated by Django 3.2.6 on 2021-08-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='licNum',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='make',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vinNum',
        ),
    ]
