# Generated by Django 3.2.6 on 2021-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210830_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='make',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
