# Generated by Django 3.2.6 on 2021-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customer_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
