# Generated by Django 3.2.6 on 2021-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210830_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
